service: user-service
frameworkVersion: '3'

provider:
  name: aws
  stage: dev
  profile: meuzi
  runtime: nodejs18.x
  timeout: 30
  versionFunctions: false
  httpApi:
    cors: true

functions:
  signup:
    handler: app/handler.signup
    events:
      - httpApi:
          path: /signup
          method: post
  login:
    handler: app/handler.login
    events:
      - httpApi:
          path: /login
          method: post
  verify:
    handler: app/handler.verify
    events:
      - httpApi:
          path: /verify
          method: get
      - httpApi:
          path: /verify
          method: post
  profile:
    handler: app/handler.profile
    events:
      - httpApi:
          path: /user
          method: post
      - httpApi:
          path: /user
          method: put
      - httpApi:
          path: /user
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
